---
apiVersion: v1
kind: Namespace
metadata:
  name: first-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: first-app
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: quay.io/rhte_2019/webapp:v1      
        ports:
        - containerPort: 80