- name: Reglas firewall
  become: true 
  ansible.posix.firewalld:  
      permanent: yes
      port: "{{ item.value.port }}/{{ item.value.protocolo}}"
      state: enabled
  with_dict:
    - "{{ rules }}"

- name: Reiniciamos el servicio de firewall
  become: true 
  service:
    name: "firewalld"  
    state: restarted
