- name: Instalar servidor nfs
  dnf:
    name: ["nfs-utils","net-tools"]
    state: present

- name: Empezar y lanzar al inicio de nfs
  service:
    name: "nfs-server"
    enabled : yes
    state: started