- name:  Modprobe
  command: modprobe br_netfilter

- name: Iniciamos el servicio de firewall
  service:
    name: "firewalld"
    enabled : yes
    state: started

- name: Configuramos el firewall para los pods
  ansible.posix.firewalld:
    masquerade : yes
    permanent: yes
    state: enabled

- name: Reiniciamos el servicio de firewall
  service:
    name: "firewalld"  
    state: restarted

- name: Crear fichero para el manjero del tráfico con el firewall
  template:
    src: k8s.j2
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: 0644

- name:  Sysctl
  command: sysctl --system