apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: webapp-nginx
  labels:
    app: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: docker.io/nginx:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80 
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        volumeMounts:
        - name: site-pvc
          mountPath: /usr/share/nginx/html
      volumes:
      - name: site-pvc
        persistentVolumeClaim:
          claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: volumes-service
    namespace: webapp-nginx
spec:
    selector:
      app: nginx-app
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: volumes-ingress
  namespace: webapp-nginx
  labels:
    app: nginx-app
  annotations:
      haproxy.org/path-rewrite: "/"
spec:
  rules:
  - host: app-marcos.unir
    http:
      paths:
      - path: /app
        pathType: "Prefix"
        backend:
          service:
            name: volumes-service
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-configmap
  namespace: webapp-nginx
data:
  servers-increment: "42"
  ssl-redirect: "OFF"